### ISSUE TITLE
2014 Things to do

### ISSUE THREAD

**Issue by pudgeball** [TrojanRobotics/Season2014#1]
## Robot Things
- [ ] Figure out how to get Servos working
- [ ] Actually implement PID code this year
- [ ] Figure out what to do about calculating distance (Camera, Ultrasonic)
- [ ] Implement SmartDashboard with useful information
- [ ] Add basic drive (arcade drive), compressor, camera pan and tilt code to the repo for fallback
## Git Things
- [ ] Understand how to pull down the code from Github (using cmd or Github.app)
- [ ] Figure out how to create a branch to write your feature (the above things)
- [ ] Figure out how to issue a pull request with that feature
## What to do
- Find something in the **Robot Things** list to work on, this means research, code snippets, etc.  Once you have all those things add comments to this issue with what you've found (including the URLs of research, code, etc)  When you're ready to add whatever you've worked on into the repo, go through the **Git Things** list.  We'll go through the pull request together and either merge it into master OR you'll go back and fix what needs to be fixed.  If we don't get to your pull request right away, pick another item from **Robot Things** and redo the process.  Don't worry about picking the same thing as someone else, the more information we have on the topics the better.

:shipit:

**Comment by gilchristad** [comment]
if ( 1 == 1 )
        {
            x = ultraSonic.getRangeMM();
            System.out.println(x);
        }
Would this be good enough for having a constant feed of the distance within the autonomous period? Matt says that I don't need the if statement because it'll loop anyways but I don't believe what that gypsy says.
