### ISSUE TITLE
San Antonio, Texas

### ISSUE THREAD

**Issue by pudgeball** [TrojanRobotics/Season2014#9]
After a meeting with the mentors this is the desired output for St. Antonio:
## Shooter
- [x] Secondary Joystick will control the main shooting action
  - The action sequence is: Move Retrieval to shooting position, open the arms (ensure they stay powered), release the winch, wait X seconds, retract the winch, close arms
- [x] Limit switches will stop the shooter
- [ ] Ultrasonic will alert the driver when in shooting range
- [ ] When the shooter is deployed, ensure that we can't move the retrieval can't move
- [ ] When the retrieval is not in position, ensure that we can't fire the shooter
## Retrieval
- [x] 3 buttons for 3 positions
  - Retrieve
  - Shoot
  - Home 
- [ ] Secondary Joystick's y axis gives full control of the retrieval
  - Ensure that it stops at maximum and minimum angles
- [x] Secondary Joystick button for opening/closing arms
- [x] Main Joystick button for belts (forward and reverse)
- [ ] Beam sensor will alert the driver to the fact of the ball, and/or  stop the belts
## Camera
- [x] Video Feedback
- [ ] Using the feedback for autonomous to determine Hot Goal
## Autonomous
- [ ] Use Ultrasonic to determine correct distance to drive
- [ ] Use PID to drive to that spot
- [ ] Look for the Hot Goal
- [ ] Shoot!
## Drive
- [ ] Try to slow down turning while keeping straight the same speed

**Comment by ghost** [comment]
# Misc
- [ ] Display gear on the smart dashboard
